/* ===================================================================
   GINÁSTICA QUIZ PRO — Banco de Dados (60 perguntas) + Imagens
   Distribuição: 20 Aparelho · 15 Movimento · 10 Categoria · 10 Regra · 5 História
   Cada pergunta tem:
     id, img (chave de IMAGENS), imagem (emoji de fallback), descricao,
     opcoes[], correta(index), categoria, dificuldade(1-3), explicacao, dica
   As imagens são fotos do Wikimedia Commons (verificadas). Se uma imagem
   falhar ao carregar, o jogo cai automaticamente no emoji correspondente.
   =================================================================== */

const IMAGENS = {
  argolas:      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Arthur_Zanetti_Rio_2016.jpg/330px-Arthur_Zanetti_Rio_2016.jpg",
  paralelas:    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/AlejandroonParallelBars.jpg/330px-AlejandroonParallelBars.jpg",
  trave:        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/WK_turnen_in_Rotterdam_Romeense_Daniele_Silivas_in_act%2C_Bestanddeelnr_934-1091.jpg/330px-WK_turnen_in_Rotterdam_Romeense_Daniele_Silivas_in_act%2C_Bestanddeelnr_934-1091.jpg",
  cavalo:       "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/2019-06-29_1st_FIG_Artistic_Gymnastics_JWCH_Men%27s_Apparatus_finals_Pommel_horse_%28Martin_Rulsch%29_080.jpg/330px-2019-06-29_1st_FIG_Artistic_Gymnastics_JWCH_Men%27s_Apparatus_finals_Pommel_horse_%28Martin_Rulsch%29_080.jpg",
  salto:        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Vault_figure.jpg/330px-Vault_figure.jpg",
  barra_fixa:   "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/FabianHambuechen-WM07.jpg/330px-FabianHambuechen-WM07.jpg",
  assimetricas: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/2019-06-28_1st_FIG_Artistic_Gymnastics_JWCH_Women%27s_All-around_competition_Subdivision_2_Uneven_bars_%28Martin_Rulsch%29_001.jpg/330px-2019-06-28_1st_FIG_Artistic_Gymnastics_JWCH_Women%27s_All-around_competition_Subdivision_2_Uneven_bars_%28Martin_Rulsch%29_001.jpg",
  solo:         "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/ESTADOS_UNIDOS_LEVAM_OURO_NA_GIN%C3%81STICA_FEMININA_POR_EQUIPES_DOS_JOGOS_OL%C3%8DMPICOS_RIO_2016_%2828263590034%29.jpg/330px-ESTADOS_UNIDOS_LEVAM_OURO_NA_GIN%C3%81STICA_FEMININA_POR_EQUIPES_DOS_JOGOS_OL%C3%8DMPICOS_RIO_2016_%2828263590034%29.jpg",
  trampolim:    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Rio_2016_Summer_Olympics_%2828558139233%29.jpg/330px-Rio_2016_Summer_Olympics_%2828558139233%29.jpg",
  ritmica:      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Brazil_Group_2016_Olympics_Test_Event_1.jpg/330px-Brazil_Group_2016_Olympics_Test_Event_1.jpg",
  acrobatica:   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Women%27s_Trio.jpg/330px-Women%27s_Trio.jpg",
  fita:         "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/%D0%93%D1%80%D0%B0%D0%BD-%D0%BF%D1%80%D0%B8_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D1%8B_%E2%80%94_2019_01.jpg/330px-%D0%93%D1%80%D0%B0%D0%BD-%D0%BF%D1%80%D0%B8_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D1%8B_%E2%80%94_2019_01.jpg",
  bola:         "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Yana_Kudryavtseva.jpg/330px-Yana_Kudryavtseva.jpg",
  arco:         "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Natalia_Gaudio_2016_Olympics_Test_Event_1.jpg/330px-Natalia_Gaudio_2016_Olympics_Test_Event_1.jpg",
  nadia:        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/25th_Laureus_World_Sports_Awards_-_Comaneci_-_240421_142851-2_crop.jpg/330px-25th_Laureus_World_Sports_Awards_-_Comaneci_-_240421_142851-2_crop.jpg",
  simone:       "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Simone_Biles_National_Team_2024.jpg/330px-Simone_Biles_National_Team_2024.jpg",
  rebeca:       "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Rebeca_Andrade_in_2023.jpg/330px-Rebeca_Andrade_in_2023.jpg",
  daiane:       "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Daiane_dos_Santos_13072007.jpg/330px-Daiane_dos_Santos_13072007.jpg",
  parada_maos:  "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/AcroDanceHandstand.jpg/330px-AcroDanceHandstand.jpg",
  espacate:     "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Szpagat_poprzeczny.jpg/330px-Szpagat_poprzeczny.jpg",
  mortal:       "https://upload.wikimedia.org/wikipedia/commons/1/1e/Saltovor1b.gif",
  olimpiadas:   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/330px-Olympic_rings_without_rims.svg.png"
};

const PERGUNTAS = [
  /* ---------------------- APARELHOS (20) ---------------------- */
  { id: 1, img: "argolas", imagem: "🤸", categoria: "Aparelho", dificuldade: 1,
    descricao: "Aparelho com dois aros circulares presos por cabos, onde o ginasta realiza movimentos de força e equilíbrio suspenso.",
    opcoes: ["Argolas", "Barra fixa", "Cavalo com alças", "Trave"], correta: 0,
    explicacao: "As argolas exigem força estática e dinâmica, sendo um aparelho exclusivamente masculino nas Olimpíadas.",
    dica: "Pense em suspensão e força." },
  { id: 2, img: "paralelas", imagem: "🟰", categoria: "Aparelho", dificuldade: 1,
    descricao: "Aparelho com duas barras paralelas na mesma altura, usado para movimentos de balanço e força.",
    opcoes: ["Barras assimétricas", "Barras paralelas", "Barra fixa", "Trave"], correta: 1,
    explicacao: "As barras paralelas são um aparelho masculino que combina balanço, força e equilíbrio.",
    dica: "Duas barras, mesma altura." },
  { id: 3, img: "trave", imagem: "➖", categoria: "Aparelho", dificuldade: 1,
    descricao: "Superfície elevada e estreita (10 cm de largura), coberta de couro, a 1,25 m do solo.",
    opcoes: ["Solo", "Mesa de salto", "Trave de equilíbrio", "Barra fixa"], correta: 2,
    explicacao: "A trave de equilíbrio é um aparelho feminino que exige enorme controle corporal e concentração.",
    dica: "Estreita e exige muito equilíbrio." },
  { id: 4, img: "cavalo", imagem: "🏇", categoria: "Aparelho", dificuldade: 2,
    descricao: "Aparelho com alças e duas pernas, sobre o qual o ginasta faz movimentos circulares com as pernas.",
    opcoes: ["Cavalo com alças", "Mesa de salto", "Trave", "Argolas"], correta: 0,
    explicacao: "O cavalo com alças é masculino e um dos aparelhos mais difíceis pelos movimentos circulares contínuos.",
    dica: "Tem alças para segurar." },
  { id: 5, img: "salto", imagem: "🧱", categoria: "Aparelho", dificuldade: 1,
    descricao: "Plataforma sobre a qual o ginasta apoia as mãos durante um salto após corrida e impulsão no trampolim.",
    opcoes: ["Trampolim olímpico", "Mesa de salto", "Trave", "Solo"], correta: 1,
    explicacao: "A mesa de salto (vault) substituiu o antigo cavalo de salto e é usada por homens e mulheres.",
    dica: "Você corre, salta e apoia as mãos nela." },
  { id: 6, img: "barra_fixa", imagem: "📏", categoria: "Aparelho", dificuldade: 1,
    descricao: "Barra horizontal única, fixada a cerca de 2,80 m de altura, usada para grandes giros.",
    opcoes: ["Barras paralelas", "Trave", "Barra fixa", "Argolas"], correta: 2,
    explicacao: "A barra fixa é masculina e famosa pelos grandes giros e soltas espetaculares.",
    dica: "Uma única barra bem alta." },
  { id: 7, img: "assimetricas", imagem: "🪜", categoria: "Aparelho", dificuldade: 2,
    descricao: "Aparelho com duas barras paralelas posicionadas em alturas diferentes.",
    opcoes: ["Barras assimétricas", "Barras paralelas", "Barra fixa", "Trave"], correta: 0,
    explicacao: "As barras assimétricas são exclusivamente femininas, com transições dinâmicas entre as duas barras.",
    dica: "Paralelas, mas em alturas diferentes." },
  { id: 8, img: "solo", imagem: "🟦", categoria: "Aparelho", dificuldade: 1,
    descricao: "Tapete quadrado de 12 x 12 m onde se realizam acrobacias e, no feminino, coreografia com música.",
    opcoes: ["Trave", "Solo", "Mesa de salto", "Trampolim"], correta: 1,
    explicacao: "O solo é praticado por ambos os sexos; no feminino há acompanhamento musical, no masculino não.",
    dica: "Um grande tapete quadrado." },
  { id: 9, img: "trampolim", imagem: "🛏️", categoria: "Aparelho", dificuldade: 2,
    descricao: "Cama elástica com molas usada em competições oficiais de saltos de grande altura.",
    opcoes: ["Mesa de salto", "Trampolim olímpico", "Solo", "Mini-tramp"], correta: 1,
    explicacao: "O trampolim olímpico estreou nos Jogos de Sydney 2000 como modalidade própria da ginástica de trampolim.",
    dica: "Molas e saltos muito altos." },
  { id: 10, img: "olimpiadas", imagem: "6️⃣", categoria: "Aparelho", dificuldade: 2,
    descricao: "Número total de aparelhos da ginástica artística masculina.",
    opcoes: ["4 aparelhos", "5 aparelhos", "6 aparelhos", "8 aparelhos"], correta: 2,
    explicacao: "Masculino: solo, cavalo com alças, argolas, salto, barras paralelas e barra fixa.",
    dica: "Conte: solo, cavalo, argolas, salto, paralelas, fixa." },
  { id: 11, img: "trave", imagem: "4️⃣", categoria: "Aparelho", dificuldade: 2,
    descricao: "Número total de aparelhos da ginástica artística feminina.",
    opcoes: ["3 aparelhos", "4 aparelhos", "5 aparelhos", "6 aparelhos"], correta: 1,
    explicacao: "Feminino: salto, barras assimétricas, trave de equilíbrio e solo.",
    dica: "Salto, assimétricas, trave e solo." },
  { id: 12, img: "fita", imagem: "🎀", categoria: "Aparelho", dificuldade: 2,
    descricao: "Aparelho da ginástica RÍTMICA composto por um bastão com uma fita comprida na ponta.",
    opcoes: ["Corda", "Fita", "Maças", "Arco"], correta: 1,
    explicacao: "A fita é um dos cinco aparelhos da ginástica rítmica, junto com arco, bola, maças e corda.",
    dica: "Forma desenhos no ar como serpentinas." },
  { id: 13, img: "bola", imagem: "⚪", categoria: "Aparelho", dificuldade: 2,
    descricao: "Aparelho esférico da ginástica RÍTMICA, lançado e equilibrado sobre o corpo.",
    opcoes: ["Arco", "Bola", "Maças", "Corda"], correta: 1,
    explicacao: "A bola da rítmica não pode ser agarrada com firmeza; deve ser equilibrada e rolada pelo corpo.",
    dica: "É redonda e rola pelo corpo." },
  { id: 14, img: "arco", imagem: "⭕", categoria: "Aparelho", dificuldade: 2,
    descricao: "Aparelho circular da ginástica RÍTMICA, atravessado pelo corpo e rolado pelo solo.",
    opcoes: ["Arco", "Bola", "Fita", "Maças"], correta: 0,
    explicacao: "O arco permite saltos por dentro, rolamentos e lançamentos altos na ginástica rítmica.",
    dica: "Um aro pelo qual o corpo passa." },
  { id: 15, img: "ritmica", imagem: "🎳", categoria: "Aparelho", dificuldade: 3,
    descricao: "Aparelho da ginástica RÍTMICA usado em pares, parecido com pequenos pinos.",
    opcoes: ["Maças", "Corda", "Bola", "Fita"], correta: 0,
    explicacao: "As maças exigem alta coordenação, sendo manipuladas em pares com lançamentos e malabarismos.",
    dica: "Parecem dois pinos usados juntos." },
  { id: 16, img: "acrobatica", imagem: "👯", categoria: "Aparelho", dificuldade: 3,
    descricao: "Modalidade da ginástica em que duplas, trios ou quartetos formam pirâmides humanas.",
    opcoes: ["Ginástica de trampolim", "Ginástica acrobática", "Ginástica rítmica", "Ginástica artística"], correta: 1,
    explicacao: "Na ginástica acrobática os atletas trabalham em grupo, equilibrando-se uns sobre os outros.",
    dica: "Pirâmides humanas e equilíbrio em duplas." },
  { id: 17, img: "ritmica", imagem: "🤾", categoria: "Aparelho", dificuldade: 3,
    descricao: "Aparelho da ginástica rítmica que pode ser de cânhamo ou sintético e é usado para saltos.",
    opcoes: ["Fita", "Corda", "Arco", "Bola"], correta: 1,
    explicacao: "A corda permite saltos e giros; continua presente nos eventos de base da ginástica rítmica.",
    dica: "Você pula sobre ela." },
  { id: 18, img: "argolas", imagem: "🧗", categoria: "Aparelho", dificuldade: 3,
    descricao: "Aparelho masculino em que o ginasta passa por fases de balanço, força e equilíbrio sem oscilar os cabos.",
    opcoes: ["Argolas", "Barras paralelas", "Barra fixa", "Cavalo com alças"], correta: 0,
    explicacao: "Nas argolas, balançar os cabos é penalizado; o 'crucifixo' (cruz) é um elemento de força clássico.",
    dica: "Cabos que não podem balançar." },
  { id: 19, img: "salto", imagem: "🏃", categoria: "Aparelho", dificuldade: 2,
    descricao: "Único aparelho disputado por homens e mulheres com a mesma técnica básica de corrida e impulsão.",
    opcoes: ["Trave", "Mesa de salto", "Barras paralelas", "Argolas"], correta: 1,
    explicacao: "A mesa de salto é comum a ambos os sexos; muda a altura, mas a mecânica de corrida-impulsão-voo é a mesma.",
    dica: "Tem corrida de aproximação." },
  { id: 20, img: "solo", imagem: "🤸‍♀️", categoria: "Aparelho", dificuldade: 1,
    descricao: "Único aparelho da ginástica artística feminina realizado com acompanhamento musical.",
    opcoes: ["Trave", "Solo", "Barras assimétricas", "Salto"], correta: 1,
    explicacao: "No solo feminino a coreografia é executada com música, valorizando expressão artística e acrobacias.",
    dica: "Tem coreografia e música." },

  /* ---------------------- MOVIMENTOS (15) ---------------------- */
  { id: 21, img: "mortal", imagem: "🔄", categoria: "Movimento", dificuldade: 2,
    descricao: "Giro completo de 360° no ar com o corpo e as pernas totalmente estendidos.",
    opcoes: ["Mortal grupado", "Mortal esticado", "Flic-flac", "Ponte"], correta: 1,
    explicacao: "No mortal esticado o corpo permanece reto durante a rotação, o que aumenta a dificuldade.",
    dica: "Mortal com o corpo bem reto." },
  { id: 22, img: "solo", imagem: "🌉", categoria: "Movimento", dificuldade: 1,
    descricao: "Movimento em que o corpo forma um arco, com mãos e pés apoiados no chão e barriga para cima.",
    opcoes: ["Ponte", "Estrela", "Roda", "Vela"], correta: 0,
    explicacao: "A ponte trabalha a flexibilidade da coluna e a força de ombros e pernas.",
    dica: "O corpo vira um arco." },
  { id: 23, img: "solo", imagem: "✂️", categoria: "Movimento", dificuldade: 2,
    descricao: "Salto com abertura ampla das pernas, lembrando uma tesoura no ar.",
    opcoes: ["Salto grupado", "Salto tesoura", "Pirueta", "Arabesque"], correta: 1,
    explicacao: "O salto tesoura exige flexibilidade e impulsão para alcançar a máxima abertura das pernas.",
    dica: "As pernas abrem como uma tesoura." },
  { id: 24, img: "solo", imagem: "🤸‍♂️", categoria: "Movimento", dificuldade: 1,
    descricao: "Movimento de rotação lateral do corpo apoiando as mãos no solo, uma de cada vez.",
    opcoes: ["Roda (estrela)", "Ponte", "Mortal", "Vela"], correta: 0,
    explicacao: "A roda, também chamada de estrela, é um dos movimentos básicos da ginástica de solo.",
    dica: "Você gira de lado tipo um cata-vento." },
  { id: 25, img: "solo", imagem: "⭐", categoria: "Movimento", dificuldade: 1,
    descricao: "Posição estática com braços estendidos para os lados e o corpo formando um X.",
    opcoes: ["Vela", "Estrela", "Prancha", "Ponte"], correta: 1,
    explicacao: "A posição de estrela é base de equilíbrio e alinhamento corporal.",
    dica: "O corpo forma um X." },
  { id: 26, img: "mortal", imagem: "↩️", categoria: "Movimento", dificuldade: 2,
    descricao: "Salto acrobático para trás com apoio das mãos no solo, em forma de cambalhota invertida.",
    opcoes: ["Flic-flac", "Mortal", "Roda", "Ponte"], correta: 0,
    explicacao: "O flic-flac (back handspring) é essencial para ligar elementos acrobáticos em sequência.",
    dica: "Cambalhota para trás passando pelas mãos." },
  { id: 27, img: "trave", imagem: "🦢", categoria: "Movimento", dificuldade: 2,
    descricao: "Equilíbrio sobre uma perna com o tronco inclinado à frente e a outra perna estendida atrás.",
    opcoes: ["Arabesque", "Pirueta", "Estrela", "Vela"], correta: 0,
    explicacao: "O arabesque é um elemento de equilíbrio muito usado na trave e no solo feminino.",
    dica: "Um pé no chão, a outra perna para trás." },
  { id: 28, img: "solo", imagem: "💫", categoria: "Movimento", dificuldade: 2,
    descricao: "Giro do corpo em torno do próprio eixo, com a perna de apoio estendida.",
    opcoes: ["Pirueta", "Mortal", "Ponte", "Flic-flac"], correta: 0,
    explicacao: "A pirueta é avaliada pelo número de voltas e pela limpeza do giro.",
    dica: "Girar sobre o próprio eixo." },
  { id: 29, img: "mortal", imagem: "🧶", categoria: "Movimento", dificuldade: 1,
    descricao: "Salto com as pernas unidas e os joelhos flexionados em direção ao peito.",
    opcoes: ["Salto esticado", "Salto grupado", "Salto tesoura", "Salto carpado"], correta: 1,
    explicacao: "No salto grupado os joelhos são levados ao peito; é a base para mortais grupados.",
    dica: "Joelhos recolhidos junto ao peito." },
  { id: 30, img: "espacate", imagem: "🙆", categoria: "Movimento", dificuldade: 3,
    descricao: "Movimento em que, da posição em pé, o ginasta arqueia o corpo para trás até a ponte.",
    opcoes: ["Ponte de pé (kickover)", "Vela", "Estrela", "Pirueta"], correta: 0,
    explicacao: "A ponte de pé exige grande flexibilidade de coluna e controle para descer e subir com segurança.",
    dica: "Descer para a ponte estando em pé." },
  { id: 31, img: "parada_maos", imagem: "🤲", categoria: "Movimento", dificuldade: 2,
    descricao: "Posição de equilíbrio invertido apoiado apenas nas mãos, com o corpo na vertical.",
    opcoes: ["Parada de mãos (bandeira)", "Vela", "Ponte", "Prancha"], correta: 0,
    explicacao: "A parada de mãos (handstand) é fundamental e aparece em praticamente todos os aparelhos.",
    dica: "De cabeça para baixo, apoiado nas mãos." },
  { id: 32, img: "argolas", imagem: "🕴️", categoria: "Movimento", dificuldade: 3,
    descricao: "Elemento de força nas argolas em que o corpo fica na horizontal, paralelo ao solo, segurando os aros.",
    opcoes: ["Crucifixo (cruz)", "Bandeira", "Pirueta", "Ponte"], correta: 0,
    explicacao: "O crucifixo (Iron Cross) é um elemento clássico de força isométrica das argolas masculinas.",
    dica: "Braços abertos formando uma cruz." },
  { id: 33, img: "mortal", imagem: "🔁", categoria: "Movimento", dificuldade: 3,
    descricao: "Mortal para trás com uma rotação completa do corpo em torno do eixo longitudinal.",
    opcoes: ["Mortal com pirueta", "Flic-flac", "Roda", "Ponte"], correta: 0,
    explicacao: "Combinar mortal (rotação para trás) com pirueta (giro lateral) é um dos elementos mais cobrados em finais.",
    dica: "Mortal + giro ao mesmo tempo." },
  { id: 34, img: "espacate", imagem: "🤺", categoria: "Movimento", dificuldade: 2,
    descricao: "Grande abertura das pernas em linha reta, com o quadril próximo ao solo.",
    opcoes: ["Espacate (espargata)", "Ponte", "Vela", "Arabesque"], correta: 0,
    explicacao: "O espacate demonstra a flexibilidade exigida em saltos e elementos de dança.",
    dica: "Abertura total das pernas no chão." },
  { id: 35, img: "salto", imagem: "🎯", categoria: "Movimento", dificuldade: 2,
    descricao: "Final de um exercício em que o ginasta deve pousar firme, sem dar passos.",
    opcoes: ["Aterrissagem (saída)", "Entrada", "Transição", "Balanço"], correta: 0,
    explicacao: "A aterrissagem firme, sem passos extras, evita deduções; cair ou dar passos custa pontos.",
    dica: "É o momento de 'cravar' o pouso." },

  /* ---------------------- CATEGORIAS (10) ---------------------- */
  { id: 36, img: "assimetricas", imagem: "🚺", categoria: "Categoria", dificuldade: 1,
    descricao: "Aparelho exclusivo da ginástica artística FEMININA com duas barras em alturas diferentes.",
    opcoes: ["Barras paralelas", "Barras assimétricas", "Cavalo com alças", "Argolas"], correta: 1,
    explicacao: "As barras assimétricas são exclusivamente femininas.", dica: "Barras em alturas diferentes." },
  { id: 37, img: "argolas", imagem: "🚹", categoria: "Categoria", dificuldade: 1,
    descricao: "Aparelho exclusivo da ginástica artística MASCULINA que usa dois aros suspensos.",
    opcoes: ["Trave", "Barras assimétricas", "Argolas", "Solo feminino"], correta: 2,
    explicacao: "As argolas são exclusivamente masculinas.", dica: "Força suspensa nos aros." },
  { id: 38, img: "solo", imagem: "⚧️", categoria: "Categoria", dificuldade: 1,
    descricao: "Aparelho presente tanto na ginástica masculina quanto na feminina.",
    opcoes: ["Trave", "Argolas", "Solo", "Barras assimétricas"], correta: 2,
    explicacao: "O solo e o salto existem em ambas as categorias (com regras diferentes).", dica: "Um grande tapete usado por todos." },
  { id: 39, img: "trave", imagem: "🚺", categoria: "Categoria", dificuldade: 1,
    descricao: "Aparelho FEMININO que exige extremo equilíbrio sobre uma superfície estreita.",
    opcoes: ["Trave de equilíbrio", "Cavalo com alças", "Argolas", "Barra fixa"], correta: 0,
    explicacao: "A trave é exclusivamente feminina e cobra concentração e equilíbrio.", dica: "Só 10 cm de largura." },
  { id: 40, img: "cavalo", imagem: "🚹", categoria: "Categoria", dificuldade: 2,
    descricao: "Aparelho MASCULINO em que o ginasta faz círculos contínuos com as pernas sobre alças.",
    opcoes: ["Cavalo com alças", "Trave", "Barras assimétricas", "Solo feminino"], correta: 0,
    explicacao: "O cavalo com alças é exclusivamente masculino.", dica: "Movimentos circulares sobre alças." },
  { id: 41, img: "paralelas", imagem: "🚹", categoria: "Categoria", dificuldade: 2,
    descricao: "Aparelho MASCULINO formado por duas barras paralelas na mesma altura.",
    opcoes: ["Barras assimétricas", "Barras paralelas", "Trave", "Salto feminino"], correta: 1,
    explicacao: "As barras paralelas são exclusivamente masculinas.", dica: "Duas barras na mesma altura." },
  { id: 42, img: "barra_fixa", imagem: "🚹", categoria: "Categoria", dificuldade: 2,
    descricao: "Aparelho MASCULINO de uma barra única e alta, famoso por giros e soltas.",
    opcoes: ["Barra fixa", "Trave", "Barras assimétricas", "Salto feminino"], correta: 0,
    explicacao: "A barra fixa é exclusivamente masculina.", dica: "Uma única barra a quase 3 metros." },
  { id: 43, img: "ritmica", imagem: "🎵", categoria: "Categoria", dificuldade: 2,
    descricao: "Categoria da ginástica em que TODOS os exercícios são feitos com música e aparelhos manuais.",
    opcoes: ["Ginástica artística", "Ginástica rítmica", "Ginástica de trampolim", "Ginástica acrobática"], correta: 1,
    explicacao: "A ginástica rítmica é praticada com música e aparelhos (arco, bola, maças, fita, corda).", dica: "Fita, bola, arco... sempre com música." },
  { id: 44, img: "trampolim", imagem: "🤸", categoria: "Categoria", dificuldade: 2,
    descricao: "Categoria olímpica que se resume a saltos de grande altura sobre uma cama elástica.",
    opcoes: ["Ginástica de trampolim", "Ginástica rítmica", "Ginástica acrobática", "Ginástica artística"], correta: 0,
    explicacao: "A ginástica de trampolim entrou no programa olímpico em Sydney 2000.", dica: "Saltos altíssimos em cama elástica." },
  { id: 45, img: "acrobatica", imagem: "🤼", categoria: "Categoria", dificuldade: 3,
    descricao: "Categoria em que os atletas se equilibram uns sobre os outros formando figuras.",
    opcoes: ["Ginástica acrobática", "Ginástica artística", "Ginástica de trampolim", "Ginástica rítmica"], correta: 0,
    explicacao: "Na ginástica acrobática há 'bases' e 'volantes' que montam pirâmides e fazem lançamentos.", dica: "Trabalho em duplas ou grupos." },

  /* ---------------------- REGRAS E PONTUAÇÃO (10) ---------------------- */
  { id: 46, img: "olimpiadas", imagem: "🔢", categoria: "Regra", dificuldade: 2,
    descricao: "Como é formada a nota final de um exercício no Código de Pontuação atual (pós-2006).",
    opcoes: ["Apenas a nota de execução (0 a 10)", "Nota de Dificuldade (D) + Nota de Execução (E)", "Média de 6 juízes", "Soma das medalhas"], correta: 1,
    explicacao: "Desde 2006 a nota = Dificuldade (sem teto fixo) + Execução (parte de 10,0 com deduções). Acabou o '10 perfeito'.", dica: "São duas notas somadas: D + E." },
  { id: 47, img: "trave", imagem: "⬇️", categoria: "Regra", dificuldade: 1,
    descricao: "Dedução padrão aplicada quando o ginasta CAI do aparelho.",
    opcoes: ["0,1 ponto", "0,3 ponto", "1,0 ponto", "5,0 pontos"], correta: 2,
    explicacao: "A queda do aparelho gera uma dedução de 1,0 ponto na nota de execução.", dica: "É a maior dedução comum, vale 1 ponto cheio." },
  { id: 48, img: "solo", imagem: "⏱️", categoria: "Regra", dificuldade: 2,
    descricao: "Tempo máximo aproximado de um exercício de solo na ginástica artística feminina.",
    opcoes: ["30 segundos", "90 segundos", "3 minutos", "5 minutos"], correta: 1,
    explicacao: "O solo feminino dura no máximo cerca de 90 segundos, com música.", dica: "É um minuto e meio." },
  { id: 49, img: "olimpiadas", imagem: "👨‍⚖️", categoria: "Regra", dificuldade: 3,
    descricao: "Os dois painéis de juízes que avaliam um exercício moderno são responsáveis por...",
    opcoes: ["Dificuldade (D) e Execução (E)", "Tempo e Altura", "Roupa e Música", "Público e TV"], correta: 0,
    explicacao: "Há um painel D (conteúdo/dificuldade) e um painel E (execução/deduções).", dica: "Pense nas letras D e E." },
  { id: 50, img: "salto", imagem: "👣", categoria: "Regra", dificuldade: 1,
    descricao: "O que acontece quando o ginasta dá um passo extra na aterrissagem (saída)?",
    opcoes: ["Ganha pontos de bônus", "Recebe uma dedução pequena", "É desclassificado", "Repete o exercício"], correta: 1,
    explicacao: "Passos ou saltos na aterrissagem geram pequenas deduções (geralmente 0,1 cada).", dica: "Cravar o pouso é o ideal; passo = penalidade." },
  { id: 51, img: "solo", imagem: "🚧", categoria: "Regra", dificuldade: 2,
    descricao: "O que é uma 'linha' (saída do limite) penalizada no solo?",
    opcoes: ["Pisar fora da área demarcada do tapete", "Errar a música", "Demorar para começar", "Trocar de roupa"], correta: 0,
    explicacao: "Pisar fora dos limites do tapete de solo gera dedução por saída de área.", dica: "Tem a ver com os limites do tapete." },
  { id: 52, img: "assimetricas", imagem: "🏅", categoria: "Regra", dificuldade: 2,
    descricao: "No individual geral (all-around) feminino, em quantos aparelhos a ginasta compete?",
    opcoes: ["2 aparelhos", "4 aparelhos", "6 aparelhos", "8 aparelhos"], correta: 1,
    explicacao: "No all-around feminino soma-se a nota dos 4 aparelhos: salto, assimétricas, trave e solo.", dica: "É o mesmo número de aparelhos femininos." },
  { id: 53, img: "argolas", imagem: "🏅", categoria: "Regra", dificuldade: 2,
    descricao: "No individual geral (all-around) masculino, em quantos aparelhos o ginasta compete?",
    opcoes: ["4 aparelhos", "5 aparelhos", "6 aparelhos", "8 aparelhos"], correta: 2,
    explicacao: "O all-around masculino soma a nota dos 6 aparelhos da categoria.", dica: "É o mesmo número de aparelhos masculinos." },
  { id: 54, img: "olimpiadas", imagem: "📈", categoria: "Regra", dificuldade: 3,
    descricao: "No Código de Pontuação atual, a nota de Dificuldade (D)...",
    opcoes: ["Tem teto máximo de 10", "Não tem teto fixo, quanto mais difícil maior", "É sempre igual para todos", "Vale só no salto"], correta: 1,
    explicacao: "A nota D cresce conforme o ginasta inclui mais elementos difíceis; não há limite fixo.", dica: "Quanto mais arriscado o exercício, mais ela sobe." },
  { id: 55, img: "solo", imagem: "🤕", categoria: "Regra", dificuldade: 2,
    descricao: "Erros de execução como pernas separadas, joelhos flexionados ou pés em ponta errada geram...",
    opcoes: ["Bônus de artisticidade", "Deduções na nota E", "Aumento da nota D", "Eliminação imediata"], correta: 1,
    explicacao: "Imperfeições de forma são descontadas na nota de Execução (E).", dica: "Forma feia desconta na execução." },

  /* ---------------------- HISTÓRIA E CURIOSIDADES (5) ---------------------- */
  { id: 56, img: "nadia", imagem: "🇷🇴", categoria: "História", dificuldade: 2,
    descricao: "Primeira ginasta a receber a nota máxima de 10,0 perfeito em uma Olimpíada (Montreal 1976).",
    opcoes: ["Nadia Comăneci", "Simone Biles", "Larisa Latynina", "Daiane dos Santos"], correta: 0,
    explicacao: "A romena Nadia Comăneci tirou o primeiro 10,0 perfeito da história olímpica, nas assimétricas, em 1976.", dica: "Romena, Montreal 1976." },
  { id: 57, img: "olimpiadas", imagem: "🏛️", categoria: "História", dificuldade: 2,
    descricao: "Edição dos Jogos Olímpicos modernos em que a ginástica esteve presente desde o início.",
    opcoes: ["Atenas 1896", "Paris 1924", "Berlim 1936", "Roma 1960"], correta: 0,
    explicacao: "A ginástica faz parte dos Jogos Olímpicos modernos desde a primeira edição, Atenas 1896.", dica: "A primeira Olimpíada moderna." },
  { id: 58, img: "simone", imagem: "🇺🇸", categoria: "História", dificuldade: 3,
    descricao: "Ginasta norte-americana considerada a maior de todos os tempos, com saltos que levam seu nome.",
    opcoes: ["Simone Biles", "Nadia Comăneci", "Rebeca Andrade", "Mary Lou Retton"], correta: 0,
    explicacao: "Simone Biles tem múltiplos elementos batizados com seu nome e é a maior medalhista mundial da ginástica.", dica: "Norte-americana, várias manobras têm o nome dela." },
  { id: 59, img: "rebeca", imagem: "🇧🇷", categoria: "História", dificuldade: 3,
    descricao: "Ginasta brasileira, primeira do país a se tornar campeã olímpica na ginástica artística.",
    opcoes: ["Daiane dos Santos", "Rebeca Andrade", "Jade Barbosa", "Flávia Saraiva"], correta: 1,
    explicacao: "Rebeca Andrade conquistou o ouro olímpico no salto em Tóquio 2020 (disputado em 2021), feito inédito para o Brasil.", dica: "Brasileira, ouro no salto em Tóquio." },
  { id: 60, img: "daiane", imagem: "🇧🇷", categoria: "História", dificuldade: 3,
    descricao: "Ginasta brasileira que deu nome a um elemento de solo (duplo twist carpado), o 'Dos Santos'.",
    opcoes: ["Daiane dos Santos", "Rebeca Andrade", "Jade Barbosa", "Flávia Saraiva"], correta: 0,
    explicacao: "Daiane dos Santos foi a primeira brasileira campeã mundial e tem um elemento de solo com seu nome.", dica: "Pioneira brasileira, elemento batizado com seu sobrenome." }
];

if (typeof window !== "undefined") {
  window.PERGUNTAS = PERGUNTAS;
  window.IMAGENS = IMAGENS;
}
